### ISSUE TITLE
Proposal: do not update revision if a value does not change

### ISSUE THREAD

**Issue by phettberg** [semiversus/python-revisiondict#4]
There are cases where the revisiondict is continuously updated with values which are polled, e.g., from some device.  However, if a poll value stays the same, the revision is still increased. My proposal is to check in `__setitem__` whether a value from an existing key has changed, and if not, leave it as is. Of course, we'd have to be careful with mutable data structures (although I don't think that's the use case).

The benefit would be, that one wouldn't need to retrieve identical data from the cache, if values from device pollings aren't changing.

What do you think  @semiversus ?

**Comment by semiversus** [comment]
Basically a good idea. One possibility would be to create an `UniqueRevisionDict` by inheriting from `RevisionDict` and overwriting `__setitem__`. Should we go this path?

**Comment by semiversus** [comment]
This should solve it. We can add it to this lib.

```python
from revisiondict import RevisionDict


class UniqueRevisionDict(RevisionDict):
    """ UniqueRevisionDict is a RevisionDict that does not increase the revision when a value is set to the
        same value as before.

        >>> d = UniqueRevisionDict()
        >>> d['a']=0; d['b']=1; d['c']=2  # make three updates
        >>> d.revision
        3
        >>> d.base_revision
        0
        >>> d['a']=0                      # update value of 'a' (was 0 before)
        >>> d.revision
        3
        >>> d['a']=3
        >>> d.revision
        4
    """
    
    def __setitem__(self, key, value):
        if key in self._key_to_index and value == self._items[self._key_to_index[key]].value:
            return
        RevisionDict.__setitem__(self, key, value)
```

**Comment by semiversus** [comment]
Added in ee3e9bf9a5cfc706a286ec091e076852fe659f12

**Comment by semiversus** [comment]
Added version 1.1.0 to python-revisiondict containing UniqueRevisionDict

**Comment by phettberg** [comment]
Oh, thanks, sorry for the late reply. I admit, that this is a pretty special use case I have, and I'm not sure if It'll improve performance. So I was a bit concerned whether it's just another wrapper for a problem, which doesn't really exist. But I guess there's no harm in providing `UniqueRevisionDict` additionally. So thank you for providing it :)
